# syntax = docker/dockerfile:1.2

RUN rm -f /etc/apt/apt.conf.d/docker-clean

############################
## Builder
############################
FROM rust:1.59 as builder

COPY . .

# create empty shell project
#RUN USER=root cargo new --bin rust-server
#WORKDIR rust-server


RUN --mount=type-cache,target=./target \
	cargo build --release
	
CMD ["./rust-server"]